#!/bin/bash

# $1 - The raw latex string
# $2 - The uuid folder for this output

cat <<EOT >> output.tex
\documentclass[tikz]{standalone}
\usepackage{tikz-feynman}
\begin{document}
\begin{tikzpicture}
EOT

# body of diagram
echo $1 >> output.tex

cat <<EOT >> output.tex
\end{tikzpicture}
\end{document}
EOT

lualatex output.tex && pdf2svg output.pdf output.svg && mv output.svg ./bind/$2/output.svg
rm /app/output.*